language: javascript
script: ./deploy.sh
install:
  - npm install -g grunt-cli
  - npm update
deploy:
  provider: releases
  api-key: fa037ff8824fe4404af3a4da7b354f661d224b03
  file:
   - indept-build.zip
   - indept-build.tar.
  skip_cleanup: true
  on:
    tags: true
    all_branches: true