language: javascript
script: ./deploy.sh
install:
  - npm install -g grunt-cli
  - npm update
deploy:
  provider: releases
  api_key:
    secure: R9r6ff/HQ/Y8yEQ1GIh0HdqvC1l+/4WbgzVX9uMTIVAGEL+XPv4cDXrzdKcyCY7pD2NmxxNiDvRvAeqcAGkrmbVfzU9jNOCvXyQrAlz0WFzsDOkC2nlXhmvZnYb7yy9F66vHBVN7Dizgpxo70tYkP0gEvGvr93VudSvDFvogAgQ=
  file:
   - indept-build.zip
   - indept-build.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: remi100756/Indept
